site_name: 'ESIIL Pre-Hackathon Training Sessions 2023'
site_description: 'Instructional material for ESIIL Hackathon 2023'
site_author: ESIIL CI team (lead = Ty Tuff)
site_url: https://cu-esiil.github.io/data-library

# Repository
repo_name: hackathon2023_datacube
repo_url: https://cu-esiil.github.io/hackathon2023_datacube
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  - Code of Conduct: Code of Conduct
  - Collaboration in the Cloud: 
    - GitHub essentials: 1_GIT_on_the_Cloud/github_lesson.md
    - CyVerse Discovery Environment: 1_GIT_on_the_Cloud/collaboration.md
    - Environmental Data Science in the Cloud: code_for_building_cube/Moving_data_in_the_cloud.md
  - Data:
    - Flood event inventory: code_for_building_cube/Pull_flood_data.md
    - Flood event area (polygons): code_for_building_cube/Pull_flood_polygons.md  
    - River geography: code_for_building_cube/Pull_river_vector_data.md
    - River and Basin features: code_for_building_cube/Pull_hydrobasins.md
    - NEON Lakes: code_for_building_cube/neon_and_lter.md
    - NEON Rivers: code_for_building_cube/neon_aquatic.md
    - EPA water quality: code_for_building_cube/epa_water_quality.md
    - USGS Water Services: code_for_building_cube/usgs_water_services.md
    - Global Species Occurrence: code_for_building_cube/iNaturalist.md
    - NEON LIDAR: code_for_building_cube/neon_lidar_and_organismal.md
    - NEON biogeochemistry: code_for_building_cube/neon.md
    - Open Street Map: code_for_building_cube/osm.md
    - US Census: code_for_building_cube/US_Census.md
    - Remote sensing: code_for_building_cube/Pull_Sentinal2_l2_data.md
  - Analytics: 
    - Artificial Intelligence (AI) for Environmental Data Science: 4_Artificial_Intelligence/artificial_intelligence_md.md

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/ESIIL_logo.png'
  favicon: 'assets/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cu-esiil/

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
